# do not create a queue: section for your test environment
test:
  adapter: postgresql
  encoding: utf8
  database: {{canvas_test_database_name}}
  host: localhost
  username: canvas
  password: {{canvas_database_password}}
  timeout: 5000

development:
  adapter: postgresql
  encoding: utf8
  database: {{canvas_database_name}}
  host: localhost
  username: {{canvas_database_user}}
  password: {{canvas_database_password}}
  timeout: 5000

production:
  adapter: postgresql
  encoding: utf8
  database: {{canvas_database_name}}
  host: localhost
  username: {{canvas_database_user}}
  password: {{canvas_database_password}}
  timeout: 5000
